### ISSUE TITLE
I am building nugets with your code.

### ISSUE THREAD

**Issue by DaneSpiritGOD** [securifybv/ShellLink#3]
I am glad that you have implement the code of create lnk file in Windows.
But I found that there is no solution in your repository and no nugets in nuget.com for use.
I create a solution of ShellLink and PropertyStore and build nuget with azure.

I am sorry for no advance inform.
If you need, I can push all my edit to your repository.
github repository: https://github.com/DaneSpiritGOD/ShellLink

**Comment by ykoster** [comment]
Hi Dane,

Glad to hear you find it useful. If you could create a pull request, I'm happy to merge it.

Thanks, Yorick
