### ISSUE TITLE
creating a shortcut to a folder

### ISSUE THREAD

**Issue by vpenades** [securifybv/ShellLink#8]
I've been able to successfully create a shortcut to a file.

But when the path points to a folder instead of a file, windows tells that the .lnk is invalid.

So, how can I create a shortcut to a folder directory?

**Comment by ykoster** [comment]
Hi @vpenades,

You can create a shortcut to a folder, by adding a LinkTargetIDList to it, eg:

```c#
new Shortcut()
{
	LinkTargetIDList = new LinkTargetIDList()
	{
		Path = @"C:\Windows\"
	}
}.WriteToFile(@"test.lnk");
```

You can always manually create the shortcut in Windows and call `Shortcut.ReadFromFile()` on it to parse & inspect it. That usually gives a good idea what is needed to programatically create the same shortcut file.

**Comment by vpenades** [comment]
It worked, thanks!
